### ISSUE TITLE
Fail to construct WebSocket on 0.4.12... but works fine on 0.3.2-SNAPSHOT

### ISSUE THREAD

**Issue by azizzaeny** [adzerk-oss/boot-reload#93] opened 2016-09-23 13:57 UTC
```js 
websocket.js:283 Uncaught SyntaxError: Failed to construct 'WebSocket': The URL 'ws://:44316' is invalid...
```
test case in electron, : https://github.com/martinklepsch/electron-and-clojurescript

what happen ?

**Comment by kenbier** [comment] 2016-09-30 00:31
Seeing the same error when upgrading to 0.4.12.

WebSocket connection to 'ws://dev.adstage.io:49604/' failed: Error during WebSocket handshake: Unexpected response code: 414

[adzerk/boot-cljs   "1.7.48-5" :scope "test"]
[adzerk/boot-reload "0.4.12"    :scope "test"]

#http://boot-clj.com
#Thu Sep 29 17:30:42 PDT 2016
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.8.0
BOOT_VERSION=2.5.2

**Comment by Deraen** [comment] 2016-10-18 21:00
Duplicate of https://github.com/adzerk-oss/boot-reload/issues/92

**Closed by Deraen** 2016-10-18 21:00 UTC
