### ISSUE TITLE
boot-reload requires Internet connection

### ISSUE THREAD

**Issue by drpheltright** [adzerk-oss/boot-reload#38] opened 2015-10-02 17:50 UTC
I'm trying to do some dev work on the train (no WiFi) and I keep getting a websocket handshake error: unexpected response code 414.

No idea if a connection is actually required just I haven't changed anything since I ran the code earlier today. Any ideas?

**Comment by drpheltright** [comment] 2015-10-02 17:53
https://drive.google.com/file/d/0B5iomZrkatQvY0haY0xnNXVZWkE/view?usp=docslist_api

**Comment by martinklepsch** [comment] 2015-10-02 18:05
@drpheltright boot-reload does not make any requests to anything outside your machine as far as I'm aware. The error you're getting could be caused by the client not being able to connect to the websocket server that has been started by the reload task. Did you get a message like the following when you started your boot task?
```
Starting reload server on ws://localhost:55804 
```

**Comment by drpheltright** [comment] 2015-10-02 21:13
Haha, just me being paranoid on the train then. Seems to not be working still. It looks like reload boots fine. Must be something wrong with my app.

```
WARNING: org.clojure/tools.nrepl version null is older than required 0.2.10
Connection is null
Writing boot_cljs_repl.cljs...
<< started reload server on ws://localhost:64528 >>
Writing boot_reload.cljs...
2015-10-02 22:09:38.244:INFO:oejs.Server:jetty-7.6.13.v20130916
2015-10-02 22:09:38.285:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:3000
<< started Jetty on http://localhost:3000 >>

Starting file watcher (CTRL-C to quit)...

nREPL server started on port 64573 on host 127.0.0.1 - nrepl://127.0.0.1:64573
Adding :require adzerk.boot-cljs-repl to main.cljs.edn...
Adding :require adzerk.boot-reload to main.cljs.edn...
Markdown changed: (about.md)
Compiling main.scss
Compiling ClojureScript...
• main.js
Elapsed time: 20.243 sec
```

**Comment by drpheltright** [comment] 2015-10-02 21:25
Right so it's working in Safari, not in Chrome. Very weird.

**Comment by martinklepsch** [comment] 2015-10-07 20:40
@drpheltright have you figured this out? Sounds like it's more likely a problem with your setup than with boot-reload?

**Comment by drpheltright** [comment] 2015-10-08 07:31
Yeah leave this with me. Chrome canary worked so will assume something is
wrong with my chrome or the actual setup of the project.

Feel free to close.

**Comment by martinklepsch** [comment] 2015-10-08 13:04
Cool. Closing this then. When you figured out what it was I'd be curious to know :)

**Closed by martinklepsch** 2015-10-08 13:04 UTC
